// <auto-generated />
namespace OnlineDiary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Notas_Usuario_Disciplina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notas_Usuario_Disciplina));
        
        string IMigrationMetadata.Id
        {
            get { return "201511151724549_Notas_Usuario_Disciplina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
